# Generated by Django 4.2.1 on 2023-09-14 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diagnostico', '0001_initial'),
        ('medidas', '0001_initial'),
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='planes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('tarifa', models.FloatField()),
                ('fechainicio', models.DateField()),
                ('fechafin', models.DateField()),
                ('modalidad', models.CharField(max_length=250)),
                ('Cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente')),
                ('Diagnostico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnostico.diagnostico')),
                ('Medidas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medidas.medidas')),
            ],
        ),
    ]
