# Generated by Django 4.2.4 on 2023-09-12 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='planes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('tarifa', models.FloatField()),
                ('fechainicio', models.DateField()),
                ('fechafin', models.DateField()),
                ('modalidad', models.CharField(max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name='cliente',
        ),
    ]
