# Generated by Django 4.2.3 on 2023-07-10 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='entrenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo', models.CharField(max_length=50)),
                ('Tarifa', models.IntegerField()),
                ('Modalidad', models.CharField(max_length=50)),
                ('Duracion', models.IntegerField()),
                ('Lista_Ejercicios', models.CharField(max_length=500)),
            ],
        ),
    ]
