# Generated by Django 4.2.4 on 2023-09-12 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrenamiento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrenamiento',
            name='imagen',
            field=models.FileField(upload_to=''),
        ),
    ]
