# Generated by Django 4.2.1 on 2023-09-14 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='Diagnostico',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='Medidas',
        ),
    ]
