# Generated by Django 4.2.4 on 2023-09-07 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='nutricion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tarifa', models.IntegerField()),
                ('Duracion', models.IntegerField()),
                ('Guia_Alimentos', models.TextField(max_length=350)),
                ('Lista_Alimentos', models.TextField(max_length=350)),
            ],
        ),
    ]
