# Generated by Django 4.2.4 on 2023-09-04 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUserForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreCompleto', models.CharField(max_length=100)),
                ('FechaInicio', models.DateField()),
                ('FechaFin', models.DateField()),
                ('FechaPago', models.DateField()),
                ('Edad', models.IntegerField()),
                ('Telefono', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254)),
                ('Domicilio', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
