# Generated by Django 4.2.1 on 2023-09-06 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_customuserform_delete_perfil'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUserForm',
        ),
    ]
