from django import forms
from apps.cliente.models import Cliente

class Clienteform(forms.ModelForm):
    class Meta:
        model=Cliente
        
        fields = [ 
            'Nombre',
            'Nacimiento',
            'Edad',
            'Genero',
            'Correo',
            'Telefono',
            'Direccion',
            'Divulgacion',
            #====
            'Altura',
            'Peso',
            'Enfermedad',
            'Info_enfermedad',
            'Cirugia',
            'Info_cirugia',
            'Dolor',
            'Info_dolor',
            'Medicamento',
            'Info_medicamento',
            'Restricciones',
            'Info_restricciones',
            'Descanso',
            'Fumas',
            'Alcohol',
            'Chequeos',
            #====
            'Rutina',
            'Alimentacion',
            'Deseo_alimentacion',
            'Hora_desayuno',
            'Hora_media_manana',
            'Hora_almuerzo',
            'Hora_media_tarde',
            'Hora_cena',
            'Agua',
            'Deporte',
            'Info_deporte',
            'Semana_deporte',
            #====
            'Nutricion',
            'Info_nutricion',
            'Alergia',
            'Info_alergia',
            'Dieta',
            'Info_dieta',
            'Macronutrientes',
            'Frutas_verduras',
            'Evitaciones',
            'Info_evitaciones',
            'Suplementacion',
            #====
            'Entrenamientos',
            'Info_entrenamientos',
            'Nivel',
            'Frecuencia',
            'Info_frecuencia',
            'Tiempo',
            'Hora',
            'Objetivo',
            'Experiencia',
            'Entorno',
            'Equipamiento',
            'Info_equipamiento',
            'Disgusto',
            #====
            'Servicio',
            'Duracion_asesoria',
            'Sesiones',
            'Preferencias',
            #====
            'Contenido',
            'Redes',
            #====
            'Fecha_inicio',
            'fecha_fin',
            'fecha_pago',
            ]
        
        labels= {
            'Nombre':'Nombre completo',
            'Nacimiento':'Fecha de nacimiento',
            'Edad':'Edad',
            'Genero':'Género',
            'Correo':'Correo electrónico',
            'Telefono':'Teléfono de contacto',
            'Direccion':'Dirección',
            'Divulgacion':'¿Cómo te enteraste de nuestros servicios?',
            'Altura':'Altura (Cm)',
            'Peso':'Peso (Kg)',
            'Enfermedad':'¿Padeces alguna enfermedad o condición médica?',
            'Info_enfermedad':'¿Cuál enfermedad padeces?',
            'Cirugia':'¿Te han practicado alguna cirugía?',
            'Info_cirugia':'Especifica el tipo de cirugía, el año en que se realizó y cualquier detalle relevante',
            'Dolor':'¿Tienes algún dolor o lesión actualmente?',
            'Info_dolor':'Describe tu dolor o lesión actual',
            'Medicamento':'¿Tomas algún medicamento regularmente?',
            'Info_medicamento':'¿Cual medicamento?',
            'Restricciones':'¿Tienes alguna restricción física o médica que deba tener en cuenta para tu entrenamiento?',
            'Info_restricciones':'Especifica tu restricción',
            'Descanso':'¿Cuántas horas duermes normalmente por noche?',
            'Fumas':'¿Fumas?',
            'Alcohol':'¿Consumes alcohol?',
            'Chequeos':'¿Con qué frecuencia te realizas chequeos médicos?',
            'Rutina':'Describe brevemente tu rutina diaria',
            'Alimentacion':'¿Cuántas veces al día sueles comer?',
            'Deseo_alimentacion':'¿Cuántas comidas preferirías hacer al día?',
            'Hora_desayuno':'¿Qué hora acostumbras para desayunar?',
            'Hora_media_manana':'¿Qué hora acostumbras tomar una media mañana?',
            'Hora_almuerzo':'¿Qué hora acostumbras para almorzar?',
            'Hora_media_tarde':'¿Qué hora acostumbras tomar una media tarde?',
            'Hora_cena':'¿Qué hora acostumbras para cenar?',
            'Agua':'¿Cuántos litros de agua consumes al día?',
            'Deporte':'¿Practicas algún deporte o actividad física actualmente?',
            'Info_deporte':'Que actividad fisica realizas',
            'Semana_deporte':'¿Cuánto tiempo dedicas a la actividad física a la semana?',
            'Nutricion':'¿Has seguido algún plan de nutrición previamente?',
            'Info_nutricion':'¿cómo te sentiste con ese plan?',
            'Alergia':'¿Tienes alguna alergia alimentaria?',
            'Info_alergia':'Cual alergia alimentaria presentas',
            'Dieta':'¿Sigues alguna dieta específica? (Ej. vegetariana, keto, sin gluten, etc.)',
            'Info_dieta':'¿Cual dieta sigues actualmente?',
            'Macronutrientes':'Selecciona tus macronutrientes preferidos (Carbohidratos, proteínas, grasas saludables)',
            'Frutas_verduras':'Describe tus futas y verduras preferidas',
            'Evitaciones':'¿Hay algún alimento que prefieres evitar?',
            'Info_evitaciones':'Que alimentos prefieres evitar',
            'Suplementacion':'¿Estás interesado en consumir suplementación?',
            'Entrenamientos':'¿Has seguido un plan de entrenamiento previamente?',
            'Info_entrenamientos':'¿cómo te sentiste con ese plan?',
            'Nivel':'¿Cuál consideras que es tu nivel de entrenamiento actual?',
            'Frecuencia':'¿Cuántos días a la semana planeas entrenar?',
            'Info_frecuencia':'¿Qué días de la semana prefieres entrenar?',
            'Tiempo':'¿Cuánto tiempo puedes dedicar por sesión de entrenamiento?',
            'Hora':'¿A qué hora del día prefieres entrenar?',
            'Objetivo':'¿Cuál es tu objetivo principal?',
            'Experiencia':'¿Tienes experiencia previa con entrenamiento físico?',
            'Entorno':'¿En qué entorno prefieres entrenar?',
            'Equipamiento':'¿Cuentas con equipamiento de entrenamiento?',
            'Info_equipamiento':'¿Qué tipo de equipamiento tienes disponible?',
            'Disgusto':'¿Hay algún ejercicio o actividad física que no te guste?',
            'Servicio':'¿Qué tipo de servicio deseas contratar?',
            'Duracion_asesoria':'Elige la duración de la Asesoría online 1A1',
            'Sesiones':'Elige el número de sesiones que te gustarian',
            'Preferencias':' ¿Tienes algún comentario o preferencia adicional respecto al servicio contratado?',
            'Contenido':'¿Cuáles son tus redes sociales preferidas para seguir contenido de fitness?',
            'Redes':'Comparte tus perfiles en redes sociales',
            'Fecha_inicio': 'Fecha de inicio',
            'fecha_fin': 'Fecha de fin',
            'fecha_pago': 'Fecha de pago',
            }
        
        widgets = {
            'Nombre': forms.TextInput(attrs={'class': 'input-user'}),
            'Nacimiento': forms.DateInput(attrs={'class': 'custom-date datepicker','type': 'text','readonly': 'readonly','placeholder': 'Selecciona una fecha'}),
            'Edad': forms.NumberInput(attrs={'class': 'input-user','min': '0','oninput': "this.value = this.value.replace(/[^0-9]/g, '');",'step': '1','inputmode': 'numeric' }),
            'Genero': forms.Select(attrs={'class': 'form-select'}),
            'Correo': forms.EmailInput(attrs={'class': ' input-user'}),
            'Telefono': forms.NumberInput(attrs={'class': 'input-user','min': '0','oninput': "this.value = this.value.replace(/[^0-9]/g, '');",'step': '1','inputmode': 'numeric' }),
            'Direccion': forms.Textarea(attrs={'class': ' input-user'}),
            'Divulgacion': forms.Select(attrs={'class': 'form-select'}),
            'Altura': forms.NumberInput(attrs={'class': 'input-user'}),
            'Peso': forms.NumberInput(attrs={'class': 'input-user'}),  # Cambié a NumberInput ya que debe ser un número
            'Enfermedad': forms.RadioSelect(choices=[(True, "Sí"), (False, "No")], attrs={'class': 'radio-custom'}),
            'Info_enfermedad': forms.TextInput(attrs={'class': 'input-user'}),
            'Cirugia': forms.RadioSelect(choices=[(True, "Sí"), (False, "No")], attrs={'class': 'radio-custom'}),
            'Info_cirugia': forms.TextInput(attrs={'class': 'input-user'}),
            'Dolor': forms.RadioSelect(choices=[(True, "Sí"), (False, "No")], attrs={'class': 'radio-custom'}),
            'Info_dolor': forms.Textarea(attrs={'class': 'input-user'}),  # Cambié a Textarea ya que puede tener más detalles
            'Medicamento': forms.RadioSelect(choices=[(True, "Sí"), (False, "No")], attrs={'class': 'radio-custom'}),
            'Info_medicamento': forms.TextInput(attrs={'class': 'input-user'}),
            'Restricciones': forms.RadioSelect(choices=[(True, "Sí"), (False, "No")], attrs={'class': 'radio-custom'}),
            'Info_restricciones': forms.TextInput(attrs={'class': 'input-user'}),
            'Descanso': forms.NumberInput(attrs={'class': 'input-user'}),  # Cambié a NumberInput si es para cantidad de horas
            'Fumas': forms.RadioSelect(choices=[(True, "Sí"), (False, "No")], attrs={'class': 'radio-custom'}),
            'Alcohol': forms.Select(choices=[(True, "Sí"), (False, "No")], attrs={'class': 'input-user'}),
            'Chequeos': forms.Select(attrs={'class': 'input-user'}),
            'Rutina': forms.Textarea(attrs={'class': ' input-user'}),
            'Alimentacion': forms.Select(attrs={'class': ' input-user'}),
            'Deseo_alimentacion': forms.Select(attrs={'class': ' input-user'}),
            'Hora_desayuno': forms.TimeInput(attrs={'class': ' input-user', 'type': 'time'}),
            'Hora_media_manana': forms.TimeInput(attrs={'class': ' input-user', 'type': 'time'}),
            'Hora_almuerzo': forms.TimeInput(attrs={'class': ' input-user', 'type': 'time'}),
            'Hora_media_tarde': forms.TimeInput(attrs={'class': ' input-user', 'type': 'time'}),
            'Hora_cena': forms.TimeInput(attrs={'class': ' input-user', 'type': 'time'}),
            'Agua': forms.NumberInput(attrs={'class': ' input-user'}),
            'Deporte': forms.RadioSelect(choices=[(True, "Sí"), (False, "No")],attrs={'class': 'radio-custom'}),
            'Info_deporte': forms.TextInput(attrs={'class': ' input-user'}),
            'Semana_deporte': forms.Select(attrs={'class': ' input-user'}),
            'Nutricion': forms.RadioSelect(choices=[(True, "Sí"), (False, "No")],attrs={'class': 'radio-custom'}),
            'Info_nutricion': forms.TextInput(attrs={'class': 'input-user'}),
            'Alergia': forms.RadioSelect(choices=[(True, "Sí"), (False, "No")],attrs={'class': 'radio-custom'}),
            'Info_alergia': forms.TextInput(attrs={'class': 'input-user'}),
            'Dieta': forms.RadioSelect(choices=[(True, "Sí"), (False, "No")],attrs={'class': 'radio-custom'}),
            'Info_dieta': forms.TextInput(attrs={'class': 'input-user'}),
            'Macronutrientes': forms.Select(attrs={'class': 'input-user' , 'id': 'Macronutrientes'}),
            'Frutas_verduras': forms.TextInput(attrs={'class': 'input-user'}),
            'Evitaciones': forms.RadioSelect(choices=[(True, "Sí"), (False, "No")],attrs={'class': 'radio-custom'}),
            'Info_evitaciones': forms.TextInput(attrs={'class': 'input-user'}),
            'Suplementacion': forms.Select(attrs={'class': ' input-user'}),
            'Entrenamientos': forms.RadioSelect(choices=[(True, "Sí"), (False, "No")],attrs={'class': 'radio-custom'}),
            'Info_entrenamientos': forms.TextInput(attrs={'class': ' input-user'}),
            'Nivel': forms.Select(attrs={'class': ' input-user'}),
            'Frecuencia': forms.Select(attrs={'class': ' input-user'}),
            'Info_frecuencia': forms.Select(attrs={'class': 'input-user'}),
            'Tiempo': forms.Select(attrs={'class': ' input-user'}),
            'Hora': forms.Select(attrs={'class': ' input-user'}),
            'Objetivo': forms.Select(attrs={'class': ' input-user'}),
            'Experiencia': forms.RadioSelect(choices=[(True, "Sí"), (False, "No")],attrs={'class': 'radio-custom'}),
            'Entorno': forms.Select(attrs={'class': ' input-user'}),
            'Equipamiento': forms.RadioSelect(choices=[(True, "Sí"), (False, "No")],attrs={'class': 'radio-custom'}),
            'Info_equipamiento': forms.Select(attrs={'class': ' input-user'}),
            'Disgusto': forms.TextInput(attrs={'class': ' input-user'}),
            'Servicio': forms.Select(attrs={'class': ' input-user'}),
            'Duracion_asesoria': forms.Select(attrs={'class': ' input-user'}),
            'Sesiones': forms.Select(attrs={'class': ' input-user'}),
            'Preferencias': forms.Textarea(attrs={'class': ' input-user'}),
            'Contenido': forms.Textarea(attrs={'class': ' input-user'}),
            'Redes': forms.Textarea(attrs={'class': ' input-user'}),
            'Fecha_inicio': forms.DateInput(attrs={'class': 'custom-date datepicker','type': 'text','readonly': 'readonly','placeholder': 'Selecciona una fecha'}),
            'fecha_fin': forms.DateInput(attrs={'class': 'custom-date datepicker','type': 'text','readonly': 'readonly','placeholder': 'Selecciona una fecha'}),
            'fecha_pago': forms.DateInput(attrs={'class': 'custom-date datepicker','type': 'text','readonly': 'readonly','placeholder': 'Selecciona una fecha'}),
            }


    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['Macronutrientes'].required = False 