from django import forms
from apps.cliente.models import cliente

class clienteform(forms.ModelForm):

    class Meta:
        model=cliente
        fields = [
            'NombreCompleto',
            'FechaInicio',
            'FechaFin',
            'FechaPago',
            'Edad',
            'Telefono',
            'Email',
            'Domicilio',
            'Objetivo_Fisico',
            'Nivel_entrenamiento_años',
            'Frecuencia_semanal',
            'Dias_de_entrenamiento',
            'Tiempo_Por_Sesion',
            'Material_Entreno',
            'Fuma',
            'Consume_alcohol',
            'Cirugias_anteriores',
            'Enfermedad_de_base',
            'Entrenos_anteriores',
            'Fracturas',
            'Tiempo_sueño',
            'Torax',
            'Brazo_Derecho',
            'Brazo_Relajado',
            'Cadera',
            'Cintura',
            'Muslo_Derecho_Contraido',
            'Pantorrilla_Derecha_Contraida',
            'Brazo_Izquierdo',
            'Muslo_Izquierdo_Contraido',
            'Pantorrilla_Izquierda_Contraida',

        ]
        labels= {
            'NombreComleto':'Nombre Completo',
            'FechaInicio':'Fecha de inicio',
            'Fecha Fin':'Fecha de finalización',
            'FechaPago':'Fecha de pago',
            'Edad': 'Edad',
            'Telefono':'Telefono',
            'Email':'Email',
            'Domicilio': 'Domicilio',
            # DIAGNISTICO
            'Objetivo_Fisico':'Objetivo Fisico',
            'Nivel_entrenamiento_años':'Nivel de entrenamiento (años)',
            'Frecuencia_semanal':'Frecuencia semanal',
            'Dias_de_entrenamiento':'Dias de entrenamiento',
            'Tiempo_Por_Sesion':'Tiempo por sesion',
            'Material_Entreno':'Material de entreno',
            'Fuma':'Fuma',
            'Consume_alcohol':'Consume alcohol',
            'Cirugias_anteriores':'Cirugias anteriores',
            'Enfermedad_de_base':'Enfermedad de base',
            'Entrenos_anteriores':'Entrenos anteriores',
            'Fracturas': 'Fracturas',
            'Tiempo_sueño':'Tiempo sueño',
            # MEDIDAS
            'Torax':'Torax',
            'Brazo_Derecho':'Brazo Derecho',
            'Brazo_Relajado':'Brazo Relajado',
            'Cadera':'Cadera',
            'Cintura':'Cintura',
            'Muslo_Derecho_Contraido':'Muslo Derecho Contraido',
            'Pantorrilla_Derecha_Contraida':'Pantorrilla Derecha Contraida',
            'Brazo_Izquierdo':'Brazo Izquierdo',
            'Muslo_Izquierdo_Contraido':'Muslo Izquierdo Contraido',
            'Pantorrilla_Izquierda_Contraida':'Pantorrilla Izquierda Contraida',
            
        }
        widgets = {
            'NombreCompleto': forms.TextInput(attrs={'class': 'form-control'}),
            'FechaInicio': forms.DateInput(attrs={'class': 'form-control'}),
            'FechaFin': forms.DateInput(attrs={'class': 'form-control'}),
            'FechaPago': forms.DateInput(attrs={'class': 'form-control'}),
            'Edad': forms.NumberInput(attrs={'class': 'form-control'}),
            'Telefono': forms.TextInput(attrs={'class': 'form-control'}),
            'Email': forms.EmailInput(attrs={'class': 'form-control'}),
            'Domicilio': forms.Textarea(attrs={'class': 'form-contrl'}),
            
            # DIAGNOSTICO
            'Objetivo_Fisico': forms.TextInput(attrs={'class': 'form-control'}),
            'Nivel_entrenamiento_años': forms.NumberInput(attrs={'class': 'form-control'}),
            'Frecuencia_semanal': forms.NumberInput(attrs={'class': 'form-control'}),
            'Dias_de_entrenamiento': forms.NumberInput(attrs={'class': 'form-control'}),
            'Tiempo_Por_Sesion': forms.NumberInput(attrs={'class': 'form-control'}),
            'Material_Entreno': forms.TextInput(attrs={'class': 'form-control'}),
            'Fuma': forms.TextInput(attrs={'class': 'form-control'}),
            'Consume_alcohol': forms.TextInput(attrs={'class': 'form-control'}),
            'Cirugias_anteriores': forms.TextInput(attrs={'class': 'form-control'}),
            'Entrenos_anteriores': forms.TextInput(attrs={'class': 'form-control'}),
            'Enfermedad_de_base': forms.TextInput(attrs={'class': 'form-control'}),
            'Fracturas': forms.TextInput(attrs={'class': 'form-control'}),
            'Tiempo_sueño': forms.NumberInput(attrs={'class': 'form-control'}),
            
            # MEDIDAS
            'Torax': forms.NumberInput(attrs={'class': 'form-control'}),
            'Brazo_Derecho': forms.NumberInput(attrs={'class': 'form-control'}),
            'Brazo_Relajado': forms.NumberInput(attrs={'class': 'form-control'}),
            'Cadera': forms.NumberInput(attrs={'class': 'form-control'}),
            'Cintura': forms.NumberInput(attrs={'class': 'form-control'}),
            'Muslo_Derecho_Contraido': forms.NumberInput(attrs={'class': 'form-control'}),
            'Pantorrilla_Derecha_Contraida': forms.NumberInput(attrs={'class': 'form-control'}),
            'Brazo_Izquierdo': forms.NumberInput(attrs={'class': 'form-control'}),
            'Muslo_Izquierdo_Contraido': forms.NumberInput(attrs={'class': 'form-control'}),
            'Pantorrilla_Izquierda_Contraida': forms.NumberInput(attrs={'class': 'form-control'}),
            
        }
