from django.db import models

class cliente(models.Model):
    
    NombreCompleto = models.CharField(max_length=100)
    FechaInicio = models.DateField()
    FechaFin = models.DateField()
    FechaPago = models.DateField()
    Edad = models.IntegerField()
    Telefono = models.CharField(max_length=20)
    Email = models.EmailField()
    Domicilio = models.CharField(max_length=200)
    Objetivo_Fisico=models.CharField(max_length=900)
    Nivel_entrenamiento_años=models.IntegerField()
    Frecuencia_semanal=models.IntegerField()
    Dias_de_entrenamiento=models.IntegerField()
    Tiempo_Por_Sesion=models.IntegerField()
    Material_Entreno=models.CharField(max_length=50)
    Fuma=models.CharField(max_length=50)
    Consume_alcohol=models.CharField(max_length=50)
    Cirugias_anteriores=models.CharField(max_length=200)
    Entrenos_anteriores=models.CharField(max_length=200)
    Enfermedad_de_base=models.CharField(max_length=200)
    Fracturas=models.CharField(max_length=50)
    Tiempo_sueño=models.IntegerField()
    Brazo_Izquierdo=models.IntegerField()
    Brazo_Derecho=models.IntegerField()
    Torax=models.IntegerField()
    Brazo_Relajado=models.IntegerField()
    Cadera=models.IntegerField()
    Cintura=models.IntegerField()
    Muslo_Derecho_Contraido=models.IntegerField()
    Muslo_Izquierdo_Contraido=models.IntegerField()
    Pantorrilla_Derecha_Contraida=models.IntegerField()
    Pantorrilla_Izquierda_Contraida=models.IntegerField()
    