# Generated by Django 4.2.3 on 2023-07-10 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='asesorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Guia_Suplemento', models.CharField(max_length=100)),
                ('Nutricion', models.TextField(max_length=350)),
                ('Tarifa', models.IntegerField()),
                ('Duracion', models.IntegerField()),
            ],
        ),
    ]
